BEGIN TRANSACTION;
DROP TABLE IF EXISTS "User";
CREATE TABLE IF NOT EXISTS "User" (
	"user_id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT UNIQUE,
	PRIMARY KEY("user_id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "Course";
CREATE TABLE IF NOT EXISTS "Course" (
	"course_id"	INTEGER NOT NULL UNIQUE,
	"title"	TEXT UNIQUE,
	PRIMARY KEY("user_id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "member";
CREATE TABLE IF NOT EXISTS "member" (
	"user_id"	INTEGER UNIQUE,
	"course_id"	INTEGER UNIQUE,
	"role"	INTEGER,
	PRIMARY KEY("user_id","course_id")
);
INSERT INTO "User" ("id","name") VALUES (1,NULL);
COMMIT;
